export type AmbientSound = {
  id: string;
  name: string;
  category: string;
  icon: string;
  type: 'noise' | 'osc' | 'chime' | 'wind' | 'rain' | 'drones';
  freq?: number;
  filter?: number;
  filterType?: BiquadFilterType;
  filterQ?: number;
  lfoRate?: number;
  lfoDepth?: number;
  description: string;
};

export type AmbientCategory = {
  id: string;
  name: string;
  icon: string;
  sounds: AmbientSound[];
};

const s = (
  id: string, name: string, category: string, icon: string,
  type: AmbientSound['type'], description: string,
  extra?: Partial<AmbientSound>
): AmbientSound => ({ id, name, category, icon, type, description, ...extra });

export const ambientCategories: AmbientCategory[] = [
  {
    id: 'nature', name: 'Nature & Weather', icon: '🌧️', sounds: [
      s('rain_light', 'Light Rain', 'nature', '🌧️', 'rain', 'Gentle drizzle on leaves', { filter: 1200 }),
      s('rain_heavy', 'Heavy Rain', 'nature', '⛈️', 'rain', 'Pouring downpour', { filter: 600 }),
      s('rain_roof', 'Rain on Roof', 'nature', '🏠', 'rain', 'Rain tapping a tin roof', { filter: 400, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('rain_window', 'Rain on Window', 'nature', '🪟', 'rain', 'Drops on glass', { filter: 1500, lfoRate: 0.5, lfoDepth: 0.1 }),
      s('rain_tent', 'Rain on Tent', 'nature', '⛺', 'rain', 'Camping in the rain', { filter: 700, lfoRate: 0.4, lfoDepth: 0.15 }),
      s('rain_umbrella', 'Rain on Umbrella', 'nature', '☂️', 'rain', 'Walking in rain', { filter: 900, lfoRate: 0.6, lfoDepth: 0.12 }),
      s('rain_gentle_night', 'Night Rain', 'nature', '🌙', 'rain', 'Rain at midnight', { filter: 1000, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('rain_forest', 'Forest Rain', 'nature', '🌲', 'rain', 'Rain through trees', { filter: 850, lfoRate: 0.2, lfoDepth: 0.18 }),
      s('storm', 'Thunderstorm', 'nature', '⛈️', 'noise', 'Rumbling storm', { filter: 300, lfoRate: 0.08, lfoDepth: 0.3 }),
      s('thunder', 'Distant Thunder', 'nature', '🌩️', 'noise', 'Low rumble', { filter: 120, lfoRate: 0.05, lfoDepth: 0.4 }),
      s('thunder_crack', 'Thunder Crack', 'nature', '⚡', 'noise', 'Sharp thunder', { filter: 80, lfoRate: 0.02, lfoDepth: 0.5 }),
      s('snow', 'Falling Snow', 'nature', '❄️', 'noise', 'Quiet snowfall', { filter: 3000 }),
      s('snow_deep', 'Deep Snow', 'nature', '🌨️', 'noise', 'Muffled silence', { filter: 3500, lfoRate: 0.03, lfoDepth: 0.05 }),
      s('blizzard', 'Blizzard', 'nature', '🌨️', 'wind', 'Howling blizzard', { filter: 800, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('wind_light', 'Gentle Breeze', 'nature', '🍃', 'wind', 'Soft wind', { filter: 700, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('wind_strong', 'Strong Wind', 'nature', '💨', 'wind', 'Gusty wind', { filter: 500, lfoRate: 0.15, lfoDepth: 0.35 }),
      s('wind_mountain', 'Mountain Wind', 'nature', '⛰️', 'wind', 'Whistling mountain air', { filter: 400, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('wind_desert', 'Desert Wind', 'nature', '🏜️', 'wind', 'Dry desert breeze', { filter: 600, lfoRate: 0.12, lfoDepth: 0.28 }),
      s('wind_canyon', 'Canyon Wind', 'nature', '🏞️', 'wind', 'Echoing canyon', { filter: 350, lfoRate: 0.08, lfoDepth: 0.32 }),
      s('fog', 'Foggy Morning', 'nature', '🌫️', 'noise', 'Misty stillness', { filter: 2500, lfoRate: 0.05, lfoDepth: 0.1 }),
    ],
  },
  {
    id: 'water', name: 'Water & Sea', icon: '🌊', sounds: [
      s('ocean_calm', 'Calm Ocean', 'water', '🌊', 'noise', 'Gentle rolling waves', { filter: 700, lfoRate: 0.12, lfoDepth: 0.3 }),
      s('ocean_waves', 'Ocean Waves', 'water', '🌊', 'noise', 'Steady waves', { filter: 600, lfoRate: 0.18, lfoDepth: 0.35 }),
      s('ocean_storm', 'Stormy Sea', 'water', '🌊', 'noise', 'Crashing waves', { filter: 350, lfoRate: 0.25, lfoDepth: 0.4 }),
      s('ocean_deep', 'Deep Ocean', 'water', '🌊', 'noise', 'Abyssal drone', { filter: 200, lfoRate: 0.05, lfoDepth: 0.2 }),
      s('ocean_shallow', 'Shallow Waters', 'water', '🌊', 'noise', 'Lapping shore', { filter: 900, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('lake', 'Calm Lake', 'water', '🏞️', 'noise', 'Still waters lapping', { filter: 1200, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('lake_morning', 'Morning Lake', 'water', '🏞️', 'noise', 'Misty lake', { filter: 1400, lfoRate: 0.06, lfoDepth: 0.12 }),
      s('river', 'Flowing River', 'water', '💧', 'noise', 'Babbling brook', { filter: 1000, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('river_fast', 'Fast River', 'water', '💧', 'noise', 'Rushing water', { filter: 1200, lfoRate: 0.4, lfoDepth: 0.22 }),
      s('stream', 'Mountain Stream', 'water', '🏞️', 'noise', 'Fast mountain creek', { filter: 1800, lfoRate: 0.4, lfoDepth: 0.15 }),
      s('stream_gentle', 'Gentle Stream', 'water', '🏞️', 'noise', 'Slow creek', { filter: 1600, lfoRate: 0.2, lfoDepth: 0.12 }),
      s('waterfall_large', 'Grand Waterfall', 'water', '💦', 'noise', 'Roaring cascade', { filter: 250, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('waterfall_small', 'Small Cascade', 'water', '💧', 'noise', 'Trickling falls', { filter: 800, lfoRate: 0.35, lfoDepth: 0.15 }),
      s('waterfall_tropical', 'Tropical Falls', 'water', '🌴', 'noise', 'Jungle waterfall', { filter: 500, lfoRate: 0.25, lfoDepth: 0.22 }),
      s('rain_puddle', 'Rain Puddle', 'water', '💧', 'rain', 'Drops in water', { filter: 2000 }),
      s('underwater', 'Underwater', 'water', '🌊', 'noise', 'Muffled deep sea', { filter: 150, lfoRate: 0.06, lfoDepth: 0.2 }),
      s('underwater_deep', 'Deep Blue', 'water', '🌊', 'noise', 'Abyssal pressure', { filter: 80, lfoRate: 0.03, lfoDepth: 0.15 }),
      s('rainforest_rain', 'Rainforest Rain', 'water', '🌴', 'rain', 'Tropical downpour', { filter: 900, lfoRate: 0.15, lfoDepth: 0.2 }),
      s('geyser', 'Geyser', 'water', '♨️', 'noise', 'Erupting steam', { filter: 600, lfoRate: 0.3, lfoDepth: 0.35 }),
      s('ice_crack', 'Cracking Ice', 'water', '🧊', 'chime', 'Frozen lake', { freq: 200, lfoRate: 0.1, lfoDepth: 0.4 }),
    ],
  },
  {
    id: 'forest', name: 'Forest & Jungle', icon: '🌲', sounds: [
      s('forest_deep', 'Deep Forest', 'forest', '🌲', 'noise', 'Dense woodland', { filter: 1500, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('forest_morning', 'Morning Forest', 'forest', '🌄', 'noise', 'Dawn chorus ambience', { filter: 1800, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('forest_night', 'Night Forest', 'forest', '🌲', 'noise', 'Dark woodland', { filter: 1000, lfoRate: 0.08, lfoDepth: 0.18 }),
      s('forest_rain', 'Wet Forest', 'forest', '🌲', 'noise', 'Damp woodland', { filter: 1200, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('forest_autumn', 'Autumn Forest', 'forest', '🍂', 'noise', 'Crisp leaves', { filter: 1600, lfoRate: 0.12, lfoDepth: 0.15 }),
      s('birds_chirp', 'Birdsong', 'forest', '🐦', 'chime', 'Cheerful chirping', { freq: 2200, lfoRate: 0.6, lfoDepth: 0.5 }),
      s('birds_dawn', 'Dawn Chorus', 'forest', '🐦', 'chime', 'Morning bird symphony', { freq: 1800, lfoRate: 0.4, lfoDepth: 0.4 }),
      s('birds_owl', 'Owl Hoot', 'forest', '🦉', 'chime', 'Nighttime owl', { freq: 300, lfoRate: 0.15, lfoDepth: 0.3 }),
      s('birds_eagle', 'Eagle Cry', 'forest', '🦅', 'chime', 'Soaring eagle', { freq: 1500, lfoRate: 0.2, lfoDepth: 0.5 }),
      s('birds_nightingale', 'Nightingale', 'forest', '🐦', 'chime', 'Evening songbird', { freq: 2600, lfoRate: 0.5, lfoDepth: 0.45 }),
      s('birds_crow', 'Crows', 'forest', '🐦‍⬛', 'chime', 'Cawing crows', { freq: 800, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('crickets', 'Crickets', 'forest', '🦗', 'chime', 'Evening crickets', { freq: 4500, lfoRate: 0.8, lfoDepth: 0.3 }),
      s('crickets_night', 'Night Crickets', 'forest', '🌙', 'chime', 'Late night chirps', { freq: 4200, lfoRate: 0.7, lfoDepth: 0.25 }),
      s('frogs', 'Frog Pond', 'forest', '🐸', 'chime', 'Croaking frogs', { freq: 500, lfoRate: 0.5, lfoDepth: 0.35 }),
      s('frogs_tropical', 'Tree Frogs', 'forest', '🐸', 'chime', 'Jungle frogs', { freq: 1800, lfoRate: 0.6, lfoDepth: 0.3 }),
      s('leaves', 'Rustling Leaves', 'forest', '🍂', 'noise', 'Leaves in the wind', { filter: 2200, lfoRate: 0.4, lfoDepth: 0.2 }),
      s('jungle', 'Jungle', 'forest', '🌴', 'noise', 'Tropical jungle', { filter: 1300, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('bamboo', 'Bamboo Grove', 'forest', '🎋', 'chime', 'Knocking bamboo', { freq: 900, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('pine_forest', 'Pine Forest', 'forest', '🌲', 'noise', 'Coniferous calm', { filter: 1700, lfoRate: 0.08, lfoDepth: 0.12 }),
      s('rainforest', 'Rainforest', 'forest', '🌴', 'noise', 'Amazon ambience', { filter: 1100, lfoRate: 0.18, lfoDepth: 0.25 }),
    ],
  },
  {
    id: 'farm', name: 'Farm & Countryside', icon: '🐄', sounds: [
      s('meadow', 'Open Meadow', 'farm', '🌷', 'noise', 'Fields of flowers', { filter: 1800, lfoRate: 0.12, lfoDepth: 0.1 }),
      s('meadow_spring', 'Spring Meadow', 'farm', '🌼', 'noise', 'Blooming fields', { filter: 2000, lfoRate: 0.1, lfoDepth: 0.12 }),
      s('horses', 'Horses', 'farm', '🐴', 'noise', 'Gentle pasture', { filter: 700, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('cows', 'Cows', 'farm', '🐄', 'chime', 'Distant mooing', { freq: 150, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('sheep', 'Sheep', 'farm', '🐑', 'chime', 'Grazing flock', { freq: 600, lfoRate: 0.15, lfoDepth: 0.15 }),
      s('chickens', 'Chickens', 'farm', '🐔', 'chime', 'Clucking hens', { freq: 1200, lfoRate: 0.5, lfoDepth: 0.2 }),
      s('rooster', 'Rooster', 'farm', '🐓', 'chime', 'Morning crow', { freq: 2000, lfoRate: 0.2, lfoDepth: 0.4 }),
      s('barn', 'Barn', 'farm', '🏚️', 'noise', 'Quiet barnyard', { filter: 600, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('countryside', 'Countryside', 'farm', '🌾', 'noise', 'Rolling hills', { filter: 1400, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('windmill', 'Windmill', 'farm', '🌬️', 'osc', 'Creaking windmill', { freq: 80, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('tractor', 'Tractor', 'farm', '🚜', 'osc', 'Distant engine', { freq: 90, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('goats', 'Goats', 'farm', '🐐', 'chime', 'Bleating goats', { freq: 700, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('bees', 'Bees', 'farm', '🐝', 'chime', 'Buzzing hive', { freq: 200, lfoRate: 1.5, lfoDepth: 0.3 }),
      s('duck_pond', 'Duck Pond', 'farm', '🦆', 'chime', 'Quacking ducks', { freq: 900, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('harvest', 'Harvest Field', 'farm', '🌾', 'noise', 'Golden wheat', { filter: 1300, lfoRate: 0.08, lfoDepth: 0.12 }),
    ],
  },
  {
    id: 'city', name: 'City & Urban', icon: '🏙️', sounds: [
      s('traffic', 'City Traffic', 'city', '🚗', 'noise', 'Urban hum', { filter: 500, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('traffic_busy', 'Busy Street', 'city', '🚦', 'noise', 'Heavy traffic', { filter: 700, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('traffic_highway', 'Highway', 'city', '🛣️', 'noise', 'Fast lanes', { filter: 600, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('subway', 'Subway', 'city', '🚇', 'noise', 'Underground rumble', { filter: 300, lfoRate: 0.15, lfoDepth: 0.3 }),
      s('subway_station', 'Subway Station', 'city', '🚉', 'noise', 'Crowded platform', { filter: 900, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('sirens', 'Distant Sirens', 'city', '🚨', 'chime', 'Far-off wail', { freq: 700, lfoRate: 0.3, lfoDepth: 0.4 }),
      s('crowd', 'City Crowd', 'city', '👥', 'noise', 'Murmuring crowd', { filter: 1100, lfoRate: 0.35, lfoDepth: 0.15 }),
      s('crowd_market', 'Market Crowd', 'city', '🛒', 'noise', 'Bustling market', { filter: 1300, lfoRate: 0.4, lfoDepth: 0.18 }),
      s('construction', 'Construction', 'city', '🏗️', 'noise', 'Building site', { filter: 400, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('night_city', 'City at Night', 'city', '🌃', 'noise', 'Quiet city night', { filter: 600, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('traffic_rain', 'Rainy Traffic', 'city', '🌧️', 'noise', 'Wet streets', { filter: 550, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('alley', 'Dark Alley', 'city', '🧱', 'noise', 'Quiet backstreet', { filter: 350, lfoRate: 0.12, lfoDepth: 0.2 }),
      s('park_urban', 'City Park', 'city', '🌳', 'noise', 'Urban green space', { filter: 1600, lfoRate: 0.15, lfoDepth: 0.12 }),
      s('square', 'Town Square', 'city', '⛲', 'noise', 'Open plaza', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('bridge', 'City Bridge', 'city', '🌉', 'noise', 'Bridge traffic', { filter: 450, lfoRate: 0.18, lfoDepth: 0.22 }),
      s('crosswalk', 'Crosswalk', 'city', '🚶', 'chime', 'Walking signal', { freq: 2500, lfoRate: 0.8, lfoDepth: 0.3 }),
      s('horn', 'Car Horns', 'city', '🚗', 'chime', 'Impatient traffic', { freq: 400, lfoRate: 0.15, lfoDepth: 0.3 }),
      s('downtown', 'Downtown', 'city', '🏢', 'noise', 'Business district', { filter: 750, lfoRate: 0.25, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'transport', name: 'Transport & Travel', icon: '🚂', sounds: [
      s('train', 'Train Ride', 'transport', '🚂', 'noise', 'Rail clatter', { filter: 400, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('train_distant', 'Distant Train', 'transport', '🚂', 'noise', 'Far-off train horn', { filter: 250, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('train_horn', 'Train Horn', 'transport', '🚂', 'chime', 'Loud whistle', { freq: 300, lfoRate: 0.1, lfoDepth: 0.4 }),
      s('train_tunnel', 'Train in Tunnel', 'transport', '🚂', 'noise', 'Underground rail', { filter: 200, lfoRate: 0.2, lfoDepth: 0.3 }),
      s('bus', 'Bus Journey', 'transport', '🚌', 'noise', 'Road travel', { filter: 600, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('bus_station', 'Bus Station', 'transport', '🚏', 'noise', 'Waiting area', { filter: 900, lfoRate: 0.25, lfoDepth: 0.18 }),
      s('plane_cabin', 'Airplane Cabin', 'transport', '✈️', 'noise', 'In-flight drone', { filter: 800, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('plane_takeoff', 'Plane Takeoff', 'transport', '✈️', 'noise', 'Engines roaring', { filter: 300, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('plane_landing', 'Plane Landing', 'transport', '✈️', 'noise', 'Descending', { filter: 500, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('boat', 'Boat Ride', 'transport', '⛵', 'noise', 'Gentle rocking', { filter: 500, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('ferry', 'Ferry', 'transport', '⛴️', 'noise', 'Water crossing', { filter: 350, lfoRate: 0.2, lfoDepth: 0.3 }),
      s('car_highway', 'Highway Drive', 'transport', '🛣️', 'noise', 'Open road', { filter: 550, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('car_rain', 'Driving in Rain', 'transport', '🌧️', 'noise', 'Wipers and rain', { filter: 650, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('car_idle', 'Idling Engine', 'transport', '🚗', 'osc', 'Stationary rumble', { freq: 80, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('helicopter', 'Helicopter', 'transport', '🚁', 'osc', 'Thumping rotor', { freq: 20, lfoRate: 8, lfoDepth: 0.1 }),
      s('motorcycle', 'Motorcycle', 'transport', '🏍️', 'osc', 'Revving engine', { freq: 90, lfoRate: 0.15, lfoDepth: 0.3 }),
      s('sailboat', 'Sailboat', 'transport', '⛵', 'noise', 'Wind in sails', { filter: 1200, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('rickshaw', 'Tuk Tuk', 'transport', '🛺', 'osc', 'Three-wheel putter', { freq: 110, lfoRate: 0.3, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'cafe', name: 'Cafes & Places', icon: '☕', sounds: [
      s('cafe', 'Coffee Shop', 'cafe', '☕', 'noise', 'Café murmur', { filter: 1000, lfoRate: 0.3, lfoDepth: 0.12 }),
      s('cafe_busy', 'Busy Cafe', 'cafe', '☕', 'noise', 'Lively coffee shop', { filter: 1200, lfoRate: 0.4, lfoDepth: 0.15 }),
      s('cafe_quiet', 'Quiet Cafe', 'cafe', '☕', 'noise', 'Peaceful corner', { filter: 1100, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('bakery', 'Bakery', 'cafe', '🥐', 'noise', 'Warm kitchen', { filter: 1400, lfoRate: 0.2, lfoDepth: 0.1 }),
      s('restaurant', 'Restaurant', 'cafe', '🍽️', 'noise', 'Dining ambience', { filter: 900, lfoRate: 0.25, lfoDepth: 0.15 }),
      s('restaurant_fine', 'Fine Dining', 'cafe', '🍷', 'noise', 'Elegant restaurant', { filter: 1100, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('bar', 'Cozy Bar', 'cafe', '🍸', 'noise', 'Evening bar', { filter: 800, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('pub', 'Pub', 'cafe', '🍺', 'noise', 'Lively pub', { filter: 750, lfoRate: 0.3, lfoDepth: 0.18 }),
      s('library', 'Library', 'cafe', '📚', 'noise', 'Silent reading', { filter: 1600, lfoRate: 0.08, lfoDepth: 0.08 }),
      s('bookshop', 'Bookshop', 'cafe', '📖', 'noise', 'Quiet pages', { filter: 1400, lfoRate: 0.1, lfoDepth: 0.1 }),
      s('tea_house', 'Tea House', 'cafe', '🍵', 'noise', 'Steaming calm', { filter: 1300, lfoRate: 0.12, lfoDepth: 0.1 }),
      s('museum', 'Museum', 'cafe', '🏛️', 'noise', 'Gallery echo', { filter: 1000, lfoRate: 0.08, lfoDepth: 0.1 }),
      s('gallery', 'Art Gallery', 'cafe', '🖼️', 'noise', 'Soft footsteps', { filter: 1200, lfoRate: 0.1, lfoDepth: 0.08 }),
      s('mall', 'Shopping Mall', 'cafe', '🛍️', 'noise', 'Retail bustle', { filter: 950, lfoRate: 0.3, lfoDepth: 0.18 }),
      s('haircut', 'Barber Shop', 'cafe', '💈', 'noise', 'Snipping and chat', { filter: 1100, lfoRate: 0.25, lfoDepth: 0.15 }),
      s('spa', 'Spa', 'cafe', '💆', 'noise', 'Relaxing treatment', { filter: 800, lfoRate: 0.1, lfoDepth: 0.1 }),
    ],
  },
  {
    id: 'home', name: 'Home & Indoor', icon: '🏠', sounds: [
      s('kitchen', 'Kitchen', 'home', '🍳', 'noise', 'Cooking sounds', { filter: 1100, lfoRate: 0.25, lfoDepth: 0.15 }),
      s('kitchen_boil', 'Boiling Pot', 'home', '🍲', 'noise', 'Bubbling water', { filter: 900, lfoRate: 0.4, lfoDepth: 0.2 }),
      s('tv', 'TV Glow', 'home', '📺', 'noise', 'Faint broadcast', { filter: 3000, lfoRate: 0.5, lfoDepth: 0.1 }),
      s('fireplace', 'Fireplace', 'home', '🔥', 'noise', 'Crackling fire', { filter: 350, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('fireplace_camp', 'Campfire', 'home', '🏕️', 'noise', 'Outdoor fire', { filter: 400, lfoRate: 0.35, lfoDepth: 0.2 }),
      s('candle', 'Candle', 'home', '🕯️', 'noise', 'Soft flicker', { filter: 300, lfoRate: 0.5, lfoDepth: 0.15 }),
      s('fan', 'Fan', 'home', '🌀', 'noise', 'Steady hum', { filter: 500, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('ac', 'Air Conditioner', 'home', '❄️', 'noise', 'Cool drone', { filter: 300, lfoRate: 0.03, lfoDepth: 0.08 }),
      s('washing', 'Washing Machine', 'home', '🧺', 'noise', 'Spinning cycle', { filter: 450, lfoRate: 0.5, lfoDepth: 0.2 }),
      s('clock', 'Ticking Clock', 'home', '🕐', 'chime', 'Steady tick', { freq: 2000, lfoRate: 1, lfoDepth: 0.5 }),
      s('clock_grandfather', 'Grandfather Clock', 'home', '🕰️', 'chime', 'Deep chime', { freq: 400, lfoRate: 0.5, lfoDepth: 0.4 }),
      s('vacuum', 'Vacuum', 'home', '🧹', 'noise', 'Cleaning drone', { filter: 600, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('shower', 'Shower', 'home', '🚿', 'noise', 'Running water', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('bath', 'Bath', 'home', '🛁', 'noise', 'Relaxing soak', { filter: 800, lfoRate: 0.15, lfoDepth: 0.12 }),
      s('attic', 'Old Attic', 'home', '🏚️', 'noise', 'Creaky and quiet', { filter: 550, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('basement', 'Basement', 'home', '🏚️', 'noise', 'Damp and low', { filter: 250, lfoRate: 0.08, lfoDepth: 0.18 }),
      s('heater', 'Heater', 'home', '♨️', 'noise', 'Warm air', { filter: 400, lfoRate: 0.05, lfoDepth: 0.12 }),
      s('coffee_maker', 'Coffee Maker', 'home', '☕', 'noise', 'Brewing drip', { filter: 1300, lfoRate: 0.3, lfoDepth: 0.15 }),
    ],
  },
  {
    id: 'kids', name: 'Children & Play', icon: '👶', sounds: [
      s('playground', 'Playground', 'kids', '🛝', 'noise', 'Children playing', { filter: 1300, lfoRate: 0.4, lfoDepth: 0.18 }),
      s('carousel', 'Carousel', 'kids', '🎠', 'chime', 'Merry-go-round', { freq: 1200, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('school', 'School Yard', 'kids', '🏫', 'noise', 'Recess noise', { filter: 1100, lfoRate: 0.35, lfoDepth: 0.2 }),
      s('baby', 'Baby Room', 'kids', '👶', 'chime', 'Soft cooing', { freq: 400, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('lullaby', 'Lullaby', 'kids', '🎵', 'chime', 'Gentle melody', { freq: 660, lfoRate: 0.15, lfoDepth: 0.15 }),
      s('toys', 'Toy Room', 'kids', '🧸', 'chime', 'Playful chimes', { freq: 1500, lfoRate: 0.5, lfoDepth: 0.3 }),
      s('swing', 'Swing Set', 'kids', ' playground', 'wind', 'Squeaking swings', { filter: 900, lfoRate: 0.4, lfoDepth: 0.3 }),
      s('slide', 'Play Slide', 'kids', '🛝', 'noise', 'Whooshing', { filter: 1500, lfoRate: 0.6, lfoDepth: 0.25 }),
      s('ball_pool', 'Ball Pit', 'kids', '🟡', 'noise', 'Splashing balls', { filter: 1200, lfoRate: 0.5, lfoDepth: 0.2 }),
      s('music_box', 'Music Box', 'kids', '🎶', 'chime', 'Tiny tinkle', { freq: 1800, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('playroom', 'Playroom', 'kids', '🧩', 'noise', 'Quiet play', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.12 }),
      s('crib', 'Nursery', 'kids', '🛏️', 'chime', 'Calm baby room', { freq: 550, lfoRate: 0.12, lfoDepth: 0.15 }),
    ],
  },
  {
    id: 'medical', name: 'Medical & Science', icon: '🏥', sounds: [
      s('hospital', 'Hospital', 'medical', '🏥', 'noise', 'Clinical calm', { filter: 700, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('heartbeat', 'Heartbeat', 'medical', '❤️', 'osc', 'Steady pulse', { freq: 60, lfoRate: 1.2, lfoDepth: 0.4 }),
      s('heartbeat_slow', 'Slow Heartbeat', 'medical', '💔', 'osc', 'Calm resting pulse', { freq: 50, lfoRate: 0.8, lfoDepth: 0.5 }),
      s('heartbeat_fast', 'Rapid Heartbeat', 'medical', '💗', 'osc', 'Excited pulse', { freq: 70, lfoRate: 1.8, lfoDepth: 0.35 }),
      s('dentist', 'Dentist', 'medical', '🦷', 'noise', 'Chair ambience', { filter: 900, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('lab', 'Laboratory', 'medical', '🔬', 'noise', 'Research hum', { filter: 1200, lfoRate: 0.1, lfoDepth: 0.12 }),
      s('scanner', 'MRI Scanner', 'medical', '🩻', 'osc', 'Pulsing scan', { freq: 1000, lfoRate: 2, lfoDepth: 0.3 }),
      s('pharmacy', 'Pharmacy', 'medical', '💊', 'noise', 'Quiet clinic', { filter: 1000, lfoRate: 0.12, lfoDepth: 0.1 }),
      s('waiting_room', 'Waiting Room', 'medical', '🪑', 'noise', 'Silent lobby', { filter: 800, lfoRate: 0.08, lfoDepth: 0.1 }),
      s('defibrillator', 'Defibrillator', 'medical', '⚡', 'chime', 'Charge tone', { freq: 1200, lfoRate: 0.5, lfoDepth: 0.4 }),
    ],
  },
  {
    id: 'sport', name: 'Sports & Stadiums', icon: '⚽', sounds: [
      s('stadium', 'Stadium', 'sport', '🏟️', 'noise', 'Crowd roar', { filter: 900, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('stadium_chant', 'Crowd Chant', 'sport', '📣', 'chime', 'Singing fans', { freq: 300, lfoRate: 0.5, lfoDepth: 0.3 }),
      s('stadium_clap', 'Stadium Clap', 'sport', '👏', 'chime', 'Applause', { freq: 1500, lfoRate: 0.8, lfoDepth: 0.35 }),
      s('gym', 'Gym', 'sport', '🏋️', 'noise', 'Workout ambience', { filter: 800, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('gym_heavy', 'Heavy Gym', 'sport', '🏋️', 'noise', 'Weights clanking', { filter: 500, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('swimming', 'Swimming Pool', 'sport', '🏊', 'noise', 'Splashing water', { filter: 1000, lfoRate: 0.4, lfoDepth: 0.2 }),
      s('boxing', 'Boxing Gym', 'sport', '🥊', 'noise', 'Training sounds', { filter: 500, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('tennis', 'Tennis Court', 'sport', '🎾', 'chime', 'Ball hits', { freq: 3000, lfoRate: 0.6, lfoDepth: 0.4 }),
      s('basketball', 'Basketball', 'sport', '🏀', 'noise', 'Indoor court', { filter: 850, lfoRate: 0.35, lfoDepth: 0.2 }),
      s('marathon', 'Marathon', 'sport', '🏃', 'noise', 'Running crowd', { filter: 700, lfoRate: 0.2, lfoDepth: 0.18 }),
      s('football', 'Football Match', 'sport', '⚽', 'noise', 'Game crowd', { filter: 850, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('skiing', 'Ski Slope', 'sport', '⛷️', 'wind', 'Cold wind swoosh', { filter: 1000, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('surfing', 'Surfing', 'sport', '🏄', 'noise', 'Wave riding', { filter: 550, lfoRate: 0.2, lfoDepth: 0.3 }),
      s('bowling', 'Bowling Alley', 'sport', '🎳', 'noise', 'Rolling balls', { filter: 600, lfoRate: 0.25, lfoDepth: 0.22 }),
    ],
  },
  {
    id: 'holiday', name: 'Holidays & Seasons', icon: '🎄', sounds: [
      s('christmas', 'Christmas Eve', 'holiday', '🎄', 'chime', 'Festive chimes', { freq: 1600, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('christmas_bells', 'Christmas Bells', 'holiday', '🔔', 'chime', 'Ringing bells', { freq: 1400, lfoRate: 0.4, lfoDepth: 0.35 }),
      s('newyear', 'New Year', 'holiday', '🎆', 'chime', 'Celebration', { freq: 900, lfoRate: 0.4, lfoDepth: 0.4 }),
      s('fireworks', 'Fireworks', 'holiday', '🎆', 'noise', 'Crackling bursts', { filter: 200, lfoRate: 0.15, lfoDepth: 0.4 }),
      s('halloween', 'Halloween', 'holiday', '🎃', 'noise', 'Spooky night', { filter: 250, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('haunted', 'Haunted House', 'holiday', '👻', 'osc', 'Eerie drone', { freq: 40, lfoRate: 0.05, lfoDepth: 0.3 }),
      s('spring', 'Spring Morning', 'holiday', '🌸', 'noise', 'Fresh blossoms', { filter: 2000, lfoRate: 0.15, lfoDepth: 0.12 }),
      s('summer', 'Summer Night', 'holiday', '☀️', 'noise', 'Warm evening', { filter: 1300, lfoRate: 0.12, lfoDepth: 0.15 }),
      s('autumn', 'Autumn Wind', 'holiday', '🍂', 'wind', 'Falling leaves', { filter: 600, lfoRate: 0.18, lfoDepth: 0.25 }),
      s('winter', 'Winter Night', 'holiday', '🌨️', 'noise', 'Cold stillness', { filter: 1800, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('easter', 'Easter Morning', 'holiday', '🐣', 'chime', 'Gentle bells', { freq: 1400, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('valentine', 'Valentine Evening', 'holiday', '💕', 'chime', 'Romantic tone', { freq: 880, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('thanksgiving', 'Thanksgiving', 'holiday', '🦃', 'noise', 'Family kitchen', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('diwali', 'Diwali', 'holiday', '🪔', 'chime', 'Festival lights', { freq: 1200, lfoRate: 0.35, lfoDepth: 0.3 }),
      s('lantern', 'Lantern Festival', 'holiday', '🏮', 'chime', 'Floating lights', { freq: 1000, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('carnival', 'Carnival', 'holiday', '🎪', 'noise', 'Festive crowd', { filter: 1100, lfoRate: 0.35, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'music', name: 'Music & Venues', icon: '🎵', sounds: [
      s('concert', 'Concert Hall', 'music', '🎼', 'noise', 'Live venue', { filter: 1200, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('jazz', 'Jazz Club', 'music', '🎷', 'chime', 'Smooth jazz', { freq: 440, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('karaoke', 'Karaoke Bar', 'music', '🎤', 'noise', 'Sing-along', { filter: 1500, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('opera', 'Opera House', 'music', '🎭', 'chime', 'Grand hall', { freq: 800, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('piano', 'Distant Piano', 'music', '🎹', 'chime', 'Soft playing', { freq: 523, lfoRate: 0.2, lfoDepth: 0.15 }),
      s('piano_jazz', 'Jazz Piano', 'music', '🎹', 'chime', 'Blue notes', { freq: 494, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('violin', 'Violin', 'music', '🎻', 'chime', 'String warmth', { freq: 659, lfoRate: 0.18, lfoDepth: 0.2 }),
      s('guitar', 'Acoustic Guitar', 'music', '🎸', 'chime', 'Gentle strum', { freq: 330, lfoRate: 0.22, lfoDepth: 0.18 }),
      s('guitar_classical', 'Classical Guitar', 'music', '🎸', 'chime', 'Spanish strings', { freq: 392, lfoRate: 0.2, lfoDepth: 0.22 }),
      s('drums', 'Distant Drums', 'music', '🥁', 'osc', 'Rhythmic beat', { freq: 100, lfoRate: 0.6, lfoDepth: 0.3 }),
      s('drums_taiko', 'Taiko Drums', 'music', '🥁', 'osc', 'Japanese drums', { freq: 80, lfoRate: 0.4, lfoDepth: 0.4 }),
      s('choir', 'Choir', 'music', '🎵', 'chime', 'Angelic voices', { freq: 700, lfoRate: 0.12, lfoDepth: 0.2 }),
      s('vinyl', 'Vinyl Crackle', 'music', '唱片', 'noise', 'Record player', { filter: 2500, lfoRate: 0.8, lfoDepth: 0.1 }),
      s('organ', 'Pipe Organ', 'music', '🎹', 'osc', 'Cathedral drone', { freq: 130, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('sitar', 'Sitar', 'music', '🪕', 'chime', 'Eastern strings', { freq: 440, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('harp', 'Harp', 'music', '🪕', 'chime', 'Heavenly pluck', { freq: 587, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('cello', 'Cello', 'music', '🎻', 'chime', 'Deep strings', { freq: 220, lfoRate: 0.15, lfoDepth: 0.2 }),
      s('flute', 'Flute', 'music', '🪈', 'chime', 'Breath melody', { freq: 880, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('saxophone', 'Saxophone', 'music', '🎷', 'chime', 'Smooth jazz horn', { freq: 392, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('banjo', 'Banjo', 'music', '🪕', 'chime', 'Country twang', { freq: 294, lfoRate: 0.25, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'space', name: 'Space & Sci-Fi', icon: '🌌', sounds: [
      s('spaceship', 'Spaceship', 'space', '🚀', 'osc', 'Engine hum', { freq: 60, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('ufo', 'UFO', 'space', '🛸', 'osc', 'Cosmic drift', { freq: 120, lfoRate: 0.12, lfoDepth: 0.3 }),
      s('cosmos', 'Cosmic Void', 'space', '🌌', 'noise', 'Deep space', { filter: 200, lfoRate: 0.05, lfoDepth: 0.15 }),
      s('warp', 'Warp Drive', 'space', '💫', 'osc', 'Hyperspace hum', { freq: 200, lfoRate: 0.5, lfoDepth: 0.4 }),
      s('blackhole', 'Black Hole', 'space', '🕳️', 'osc', 'Gravity well', { freq: 30, lfoRate: 0.03, lfoDepth: 0.2 }),
      s('satellite', 'Satellite', 'space', '🛰️', 'chime', 'Orbital signal', { freq: 2400, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('mars', 'Mars Wind', 'space', '🔴', 'wind', 'Martian breeze', { filter: 300, lfoRate: 0.12, lfoDepth: 0.3 }),
      s('station', 'Space Station', 'space', '🛰️', 'noise', 'ISS ambience', { filter: 500, lfoRate: 0.1, lfoDepth: 0.12 }),
      s('alien', 'Alien World', 'space', '👽', 'chime', 'Otherworldly', { freq: 550, lfoRate: 0.25, lfoDepth: 0.35 }),
      s('pulsar', 'Pulsar', 'space', '⭐', 'osc', 'Pulsing star', { freq: 800, lfoRate: 1.5, lfoDepth: 0.5 }),
      s('nebula', 'Nebula', 'space', '☁️', 'noise', 'Cosmic cloud', { filter: 400, lfoRate: 0.06, lfoDepth: 0.2 }),
      s('moon', 'Moon Surface', 'space', '🌕', 'noise', 'Silent crater', { filter: 150, lfoRate: 0.02, lfoDepth: 0.1 }),
      s('reactor', 'Reactor Core', 'space', '⚛️', 'osc', 'Energy hum', { freq: 100, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('forcefield', 'Force Field', 'space', '🛡️', 'osc', 'Energy barrier', { freq: 300, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('droid', 'Droid Workshop', 'space', '🤖', 'noise', 'Robot repairs', { filter: 1400, lfoRate: 0.25, lfoDepth: 0.2 }),
      s('cryo', 'Cryo Chamber', 'space', '🧊', 'osc', 'Frozen sleep', { freq: 50, lfoRate: 0.05, lfoDepth: 0.15 }),
      s('teleport', 'Teleporter', 'space', '🌀', 'osc', 'Beaming up', { freq: 1500, lfoRate: 0.8, lfoDepth: 0.5 }),
      s('orbit', 'Low Orbit', 'space', '🌍', 'noise', 'Earth from above', { filter: 300, lfoRate: 0.08, lfoDepth: 0.15 }),
    ],
  },
  {
    id: 'meditation', name: 'Meditation & Calm', icon: '🧘', sounds: [
      s('singing_bowl', 'Singing Bowl', 'meditation', '🪔', 'chime', 'Healing tone', { freq: 432, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('om', 'Om Chant', 'meditation', '🕉️', 'osc', 'Deep resonance', { freq: 110, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('drone_deep', 'Deep Drone', 'meditation', '🌀', 'osc', 'Meditation hum', { freq: 70, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('drone_high', 'High Drone', 'meditation', '✨', 'osc', 'Floating tone', { freq: 220, lfoRate: 0.07, lfoDepth: 0.12 }),
      s('wind_chimes', 'Wind Chimes', 'meditation', '🎐', 'chime', 'Gentle chimes', { freq: 1320, lfoRate: 0.35, lfoDepth: 0.4 }),
      s('tibetan', 'Tibetan Bowl', 'meditation', '🪷', 'chime', 'Sacred resonance', { freq: 330, lfoRate: 0.06, lfoDepth: 0.2 }),
      s('breath', 'Breathing', 'meditation', '🌬️', 'noise', 'Slow breath waves', { filter: 600, lfoRate: 0.15, lfoDepth: 0.4 }),
      s('reiki', 'Reiki', 'meditation', '🤲', 'chime', 'Healing frequency', { freq: 528, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('forest_calm', 'Zen Garden', 'meditation', '🎍', 'noise', 'Peaceful garden', { filter: 1700, lfoRate: 0.08, lfoDepth: 0.1 }),
      s('ocean_meditation', 'Ocean Meditation', 'meditation', '🌊', 'noise', 'Breathing waves', { filter: 500, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('solfege', 'Solfege Tone', 'meditation', '🎶', 'chime', 'Sacred scale', { freq: 852, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('chakra', 'Chakra Tone', 'meditation', '🌈', 'chime', 'Energy center', { freq: 396, lfoRate: 0.06, lfoDepth: 0.15 }),
      s('drone_earth', 'Earth Drone', 'meditation', '🌍', 'osc', 'Grounding hum', { freq: 174, lfoRate: 0.04, lfoDepth: 0.12 }),
      s('drone_crown', 'Crown Drone', 'meditation', '👑', 'osc', 'Spiritual tone', { freq: 963, lfoRate: 0.06, lfoDepth: 0.1 }),
      s('monk_chant', 'Monk Chant', 'meditation', '📿', 'osc', 'Temple chant', { freq: 90, lfoRate: 0.08, lfoDepth: 0.25 }),
      s('incense', 'Incense Calm', 'meditation', '🪔', 'noise', 'Smoke and stillness', { filter: 400, lfoRate: 0.03, lfoDepth: 0.1 }),
    ],
  },
  {
    id: 'industrial', name: 'Industrial & Machinery', icon: '⚙️', sounds: [
      s('factory', 'Factory', 'industrial', '🏭', 'noise', 'Machinery hum', { filter: 500, lfoRate: 0.3, lfoDepth: 0.25 }),
      s('engine', 'Engine Room', 'industrial', '🔧', 'osc', 'Deep engine', { freq: 70, lfoRate: 0.15, lfoDepth: 0.2 }),
      s('generator', 'Generator', 'industrial', '⚡', 'osc', 'Power drone', { freq: 120, lfoRate: 0.1, lfoDepth: 0.15 }),
      s('turbine', 'Turbine', 'industrial', '🌀', 'noise', 'Spinning blades', { filter: 700, lfoRate: 0.2, lfoDepth: 0.2 }),
      s('machine_shop', 'Machine Shop', 'industrial', '🔩', 'noise', 'Metal work', { filter: 900, lfoRate: 0.25, lfoDepth: 0.25 }),
      s('server_room', 'Server Room', 'industrial', '🖥️', 'noise', 'Cooling fans', { filter: 1200, lfoRate: 0.08, lfoDepth: 0.1 }),
      s('power_plant', 'Power Plant', 'industrial', '🔌', 'osc', 'Electrical hum', { freq: 50, lfoRate: 0.05, lfoDepth: 0.15 }),
      s('mining', 'Mine Shaft', 'industrial', '⛏️', 'noise', 'Deep underground', { filter: 300, lfoRate: 0.15, lfoDepth: 0.3 }),
      s('oil_rig', 'Oil Rig', 'industrial', '🛢️', 'noise', 'Offshore platform', { filter: 400, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('sawmill', 'Sawmill', 'industrial', '🪚', 'noise', 'Cutting wood', { filter: 600, lfoRate: 0.3, lfoDepth: 0.3 }),
      s('printing', 'Printing Press', 'industrial', '🖨️', 'noise', 'Rolling press', { filter: 800, lfoRate: 0.35, lfoDepth: 0.2 }),
      s('welding', 'Welding Shop', 'industrial', '🔥', 'noise', 'Sparks flying', { filter: 700, lfoRate: 0.2, lfoDepth: 0.3 }),
      s('conveyor', 'Conveyor Belt', 'industrial', '📦', 'noise', 'Assembly line', { filter: 550, lfoRate: 0.25, lfoDepth: 0.15 }),
      s('dam', 'Hydroelectric Dam', 'industrial', '💧', 'noise', 'Water and turbines', { filter: 350, lfoRate: 0.15, lfoDepth: 0.25 }),
    ],
  },
  {
    id: 'weather', name: 'Weather Mix', icon: '⛅', sounds: [
      s('rain_wind', 'Rain & Wind', 'weather', '🌧️', 'noise', 'Stormy mix', { filter: 650, lfoRate: 0.25, lfoDepth: 0.3 }),
      s('rain_thunder', 'Rain & Thunder', 'weather', '⛈️', 'noise', 'Thunderstorm', { filter: 400, lfoRate: 0.12, lfoDepth: 0.35 }),
      s('snow_wind', 'Snow & Wind', 'weather', '🌨️', 'noise', 'Winter storm', { filter: 1500, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('fog_birds', 'Fog & Birds', 'weather', '🌫️', 'noise', 'Misty morning', { filter: 2200, lfoRate: 0.12, lfoDepth: 0.15 }),
      s('rain_calm', 'Light Rain & Calm', 'weather', '🌦️', 'rain', 'Peaceful drizzle', { filter: 1400, lfoRate: 0.1, lfoDepth: 0.12 }),
      s('storm_ocean', 'Storm & Ocean', 'weather', '🌊', 'noise', 'Sea storm', { filter: 350, lfoRate: 0.2, lfoDepth: 0.35 }),
      s('wind_rain_heavy', 'Heavy Wind & Rain', 'weather', '⛈️', 'noise', 'Violent storm', { filter: 500, lfoRate: 0.3, lfoDepth: 0.4 }),
      s('sun_rain', 'Sunshower', 'weather', '🌤️', 'rain', 'Rain with sunshine', { filter: 1600, lfoRate: 0.15, lfoDepth: 0.1 }),
      s('hail', 'Hailstorm', 'weather', '🧊', 'noise', 'Ice on roof', { filter: 1200, lfoRate: 0.5, lfoDepth: 0.3 }),
      s('heat_wave', 'Heat Haze', 'weather', '🥵', 'noise', 'Dry shimmer', { filter: 200, lfoRate: 0.03, lfoDepth: 0.08 }),
    ],
  },
  {
    id: 'night', name: 'Night & Sleep', icon: '🌙', sounds: [
      s('night_quiet', 'Quiet Night', 'night', '🌙', 'noise', 'Peaceful darkness', { filter: 200, lfoRate: 0.05, lfoDepth: 0.1 }),
      s('night_crickets', 'Night Crickets', 'night', '🦗', 'chime', 'Evening chorus', { freq: 4300, lfoRate: 0.7, lfoDepth: 0.25 }),
      s('night_owl', 'Night Owl', 'night', '🦉', 'chime', 'Lone hoot', { freq: 280, lfoRate: 0.12, lfoDepth: 0.25 }),
      s('night_wolves', 'Distant Wolves', 'night', '🐺', 'chime', 'Howling pack', { freq: 350, lfoRate: 0.15, lfoDepth: 0.35 }),
      s('night_rain', 'Night Rain', 'night', '🌧️', 'rain', 'Rain for sleep', { filter: 1000, lfoRate: 0.12, lfoDepth: 0.1 }),
      s('night_wind', 'Night Wind', 'night', '🍃', 'wind', 'Gentle night breeze', { filter: 600, lfoRate: 0.12, lfoDepth: 0.2 }),
      s('night_ocean', 'Night Beach', 'night', '🌊', 'noise', 'Dark waves', { filter: 550, lfoRate: 0.1, lfoDepth: 0.25 }),
      s('night_forest', 'Night Forest', 'night', '🌲', 'noise', 'Dark woods', { filter: 900, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('night_city', 'Night City', 'night', '🌃', 'noise', 'Sleeping metropolis', { filter: 500, lfoRate: 0.06, lfoDepth: 0.12 }),
      s('night_camp', 'Camp Night', 'night', '⛺', 'noise', 'Tent and crickets', { filter: 1100, lfoRate: 0.15, lfoDepth: 0.18 }),
      s('night_snow', 'Snowy Night', 'night', '❄️', 'noise', 'Silent snowfall', { filter: 2800, lfoRate: 0.04, lfoDepth: 0.08 }),
      s('night_desert', 'Desert Night', 'night', '🏜️', 'noise', 'Cold desert', { filter: 400, lfoRate: 0.06, lfoDepth: 0.15 }),
    ],
  },
  {
    id: 'animals', name: 'Animals & Wildlife', icon: '🐾', sounds: [
      s('wolves_howl', 'Howling Wolves', 'animals', '🐺', 'chime', 'Pack howl', { freq: 350, lfoRate: 0.15, lfoDepth: 0.35 }),
      s('whale_song', 'Whale Song', 'animals', '🐋', 'osc', 'Ocean giants', { freq: 80, lfoRate: 0.08, lfoDepth: 0.3 }),
      s('dolphin', 'Dolphins', 'animals', '🐬', 'chime', 'Clicking and squeaks', { freq: 3000, lfoRate: 0.6, lfoDepth: 0.4 }),
      s('lion_roar', 'Distant Lion', 'animals', '🦁', 'osc', 'Savanna roar', { freq: 90, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('elephant', 'Elephants', 'animals', '🐘', 'osc', 'Trumpeting', { freq: 120, lfoRate: 0.08, lfoDepth: 0.25 }),
      s('monkey', 'Monkeys', 'animals', '🐒', 'chime', 'Jungle calls', { freq: 1200, lfoRate: 0.4, lfoDepth: 0.3 }),
      s('bird_hawk', 'Hawk Cry', 'animals', '🦅', 'chime', 'Screeching hawk', { freq: 1600, lfoRate: 0.25, lfoDepth: 0.5 }),
      s('bird_seagull', 'Seagulls', 'animals', '🦈', 'chime', 'Coastal calls', { freq: 1400, lfoRate: 0.3, lfoDepth: 0.35 }),
      s('insects', 'Insects', 'animals', '🐜', 'chime', 'Buzzing swarm', { freq: 3000, lfoRate: 1, lfoDepth: 0.2 }),
      s('mosquito', 'Mosquito', 'animals', '🦟', 'chime', 'Annoying buzz', { freq: 600, lfoRate: 0.5, lfoDepth: 0.15 }),
      s('fly', 'Housefly', 'animals', '🪰', 'chime', 'Lazy buzz', { freq: 400, lfoRate: 0.3, lfoDepth: 0.1 }),
      s('cricket_single', 'Single Cricket', 'animals', '🦗', 'chime', 'One chirp', { freq: 4800, lfoRate: 0.9, lfoDepth: 0.2 }),
      s('cat_purr', 'Cat Purring', 'animals', '🐱', 'osc', 'Contented hum', { freq: 25, lfoRate: 0.5, lfoDepth: 0.1 }),
      s('dog_bark', 'Distant Dog', 'animals', '🐕', 'chime', 'Barking', { freq: 500, lfoRate: 0.3, lfoDepth: 0.4 }),
    ],
  },
  {
    id: 'beach', name: 'Beach & Tropical', icon: '🏖️', sounds: [
      s('beach', 'Sandy Beach', 'beach', '🏖️', 'noise', 'Waves and sand', { filter: 650, lfoRate: 0.15, lfoDepth: 0.28 }),
      s('beach_tropical', 'Tropical Beach', 'beach', '🏝️', 'noise', 'Paradise shore', { filter: 700, lfoRate: 0.18, lfoDepth: 0.3 }),
      s('beach_sunset', 'Beach Sunset', 'beach', '🌅', 'noise', 'Evening shore', { filter: 600, lfoRate: 0.12, lfoDepth: 0.25 }),
      s('beach_storm', 'Stormy Beach', 'beach', '⛈️', 'noise', 'Windy coast', { filter: 400, lfoRate: 0.25, lfoDepth: 0.35 }),
      s('palm_trees', 'Palm Trees', 'beach', '🌴', 'wind', 'Rustling palms', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.25 }),
      s('seagulls', 'Seagulls', 'beach', '🐦', 'chime', 'Coastal birds', { freq: 1500, lfoRate: 0.3, lfoDepth: 0.35 }),
      s('tiki_bar', 'Tiki Bar', 'beach', '🍹', 'noise', 'Beach bar', { filter: 950, lfoRate: 0.25, lfoDepth: 0.15 }),
      s('hammock', 'Hammock Breeze', 'beach', '🌴', 'wind', 'Lazy swaying', { filter: 800, lfoRate: 0.1, lfoDepth: 0.18 }),
      s('coral_reef', 'Coral Reef', 'beach', '🪸', 'noise', 'Underwater life', { filter: 1200, lfoRate: 0.15, lfoDepth: 0.2 }),
      s('island', 'Deserted Island', 'beach', '🏝️', 'noise', 'Remote paradise', { filter: 550, lfoRate: 0.12, lfoDepth: 0.22 }),
      s('surf_gentle', 'Gentle Surf', 'beach', '🌊', 'noise', 'Soft breaking', { filter: 750, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('bonfire_beach', 'Beach Bonfire', 'beach', '🔥', 'noise', 'Crackling fire', { filter: 380, lfoRate: 0.3, lfoDepth: 0.25 }),
    ],
  },
  {
    id: 'world', name: 'World & Places', icon: '🌍', sounds: [
      s('market_asian', 'Asian Market', 'world', '🛍️', 'noise', 'Bustling bazaar', { filter: 1200, lfoRate: 0.35, lfoDepth: 0.2 }),
      s('market_spice', 'Spice Market', 'world', '🌶️', 'noise', 'Colorful stalls', { filter: 1100, lfoRate: 0.3, lfoDepth: 0.18 }),
      s('temple', 'Temple', 'world', '🛕', 'chime', 'Sacred bells', { freq: 600, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('mosque', 'Mosque Call', 'world', '🕌', 'chime', 'Distant prayer', { freq: 400, lfoRate: 0.08, lfoDepth: 0.25 }),
      s('church_bells', 'Church Bells', 'world', '⛪', 'chime', 'Sunday morning', { freq: 800, lfoRate: 0.2, lfoDepth: 0.3 }),
      s('indian_street', 'Indian Street', 'world', '🇮🇳', 'noise', 'Chaos and color', { filter: 900, lfoRate: 0.35, lfoDepth: 0.25 }),
      s('tokyo', 'Tokyo Street', 'world', '🗾', 'noise', 'Neon city', { filter: 1000, lfoRate: 0.3, lfoDepth: 0.2 }),
      s('paris_cafe', 'Paris Cafe', 'world', '🇫🇷', 'noise', 'French sidewalk', { filter: 1050, lfoRate: 0.2, lfoDepth: 0.12 }),
      s('venice', 'Venice Canal', 'world', '🚤', 'noise', 'Water and echoes', { filter: 500, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('sauna', 'Finnish Sauna', 'world', '🧖', 'noise', 'Steam and heat', { filter: 600, lfoRate: 0.08, lfoDepth: 0.12 }),
      s('mountain_village', 'Mountain Village', 'world', '🏔️', 'noise', 'Alpine quiet', { filter: 1300, lfoRate: 0.1, lfoDepth: 0.12 }),
      s('rainforest_village', 'Jungle Village', 'world', '🌴', 'noise', 'Remote settlement', { filter: 1000, lfoRate: 0.2, lfoDepth: 0.22 }),
      s('airport', 'Airport Terminal', 'world', '✈️', 'noise', 'Travelers and gates', { filter: 850, lfoRate: 0.25, lfoDepth: 0.18 }),
      s('train_station_europe', 'European Station', 'world', '🚉', 'noise', 'Grand hall', { filter: 800, lfoRate: 0.2, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'fantasy', name: 'Fantasy & Magic', icon: '🪄', sounds: [
      s('enchantment', 'Enchantment', 'fantasy', '✨', 'chime', 'Magic sparkles', { freq: 2000, lfoRate: 0.4, lfoDepth: 0.4 }),
      s('castle', 'Wizard Castle', 'fantasy', '🏰', 'noise', 'Ancient halls', { filter: 500, lfoRate: 0.08, lfoDepth: 0.15 }),
      s('dragon', 'Distant Dragon', 'fantasy', '🐉', 'osc', 'Deep roar', { freq: 45, lfoRate: 0.06, lfoDepth: 0.3 }),
      s('fairy', 'Fairy Dust', 'fantasy', '🧚', 'chime', 'Tinkling magic', { freq: 2800, lfoRate: 0.6, lfoDepth: 0.35 }),
      s('portal', 'Magic Portal', 'fantasy', '🌀', 'osc', 'Swirling energy', { freq: 400, lfoRate: 0.4, lfoDepth: 0.4 }),
      s('crystal', 'Crystal Cave', 'fantasy', '💎', 'chime', 'Resonant gems', { freq: 1100, lfoRate: 0.12, lfoDepth: 0.25 }),
      s('spell', 'Casting Spell', 'fantasy', '🔮', 'chime', 'Mystic incantation', { freq: 700, lfoRate: 0.3, lfoDepth: 0.35 }),
      s('unicorn', 'Unicorn Glade', 'fantasy', '🦄', 'chime', 'Enchanted meadow', { freq: 1500, lfoRate: 0.15, lfoDepth: 0.2 }),
      s('dragon_cave', 'Dragon Lair', 'fantasy', '🐉', 'noise', 'Deep cave rumble', { filter: 150, lfoRate: 0.05, lfoDepth: 0.25 }),
      s('potion', 'Potion Brewing', 'fantasy', '🧪', 'noise', 'Bubbling cauldron', { filter: 800, lfoRate: 0.4, lfoDepth: 0.3 }),
      s('elf_forest', 'Elven Forest', 'fantasy', '🧝', 'noise', 'Magical woods', { filter: 1800, lfoRate: 0.12, lfoDepth: 0.18 }),
      s('ancient_rune', 'Ancient Runes', 'fantasy', '🔮', 'chime', 'Humming stone', { freq: 500, lfoRate: 0.08, lfoDepth: 0.2 }),
    ],
  },
  {
    id: 'horror', name: 'Horror & Spooky', icon: '👻', sounds: [
      s('creepy', 'Creepy Ambience', 'horror', '👻', 'noise', 'Unsettling drone', { filter: 200, lfoRate: 0.05, lfoDepth: 0.3 }),
      s('whispers', 'Whispers', 'horror', '🤫', 'noise', 'Ghostly voices', { filter: 800, lfoRate: 0.15, lfoDepth: 0.25 }),
      s('creak', 'Creaking House', 'horror', '🏚️', 'chime', 'Groaning wood', { freq: 200, lfoRate: 0.1, lfoDepth: 0.3 }),
      s('wind_horror', 'Eerie Wind', 'horror', '💨', 'wind', 'Howling gale', { filter: 400, lfoRate: 0.08, lfoDepth: 0.35 }),
      s('dripping', 'Dripping Water', 'horror', '💧', 'chime', 'Cave drips', { freq: 1000, lfoRate: 0.3, lfoDepth: 0.4 }),
      s('chains', 'Rattling Chains', 'horror', '⛓️', 'chime', 'Metal clank', { freq: 300, lfoRate: 0.2, lfoDepth: 0.35 }),
      s('heartbeat_horror', 'Fear Heartbeat', 'horror', '💔', 'osc', 'Racing pulse', { freq: 60, lfoRate: 2, lfoDepth: 0.5 }),
      s('fog_horn', 'Fog Horn', 'horror', '🚢', 'osc', 'Deep warning', { freq: 70, lfoRate: 0.1, lfoDepth: 0.4 }),
      s('basement_dark', 'Dark Basement', 'horror', '🏚️', 'noise', 'Oppressing silence', { filter: 150, lfoRate: 0.03, lfoDepth: 0.2 }),
      s('ghost', 'Ghostly Moan', 'horror', '👻', 'osc', 'Wailing spirit', { freq: 200, lfoRate: 0.2, lfoDepth: 0.4 }),
    ],
  },
  {
    id: 'retro', name: 'Vintage & Retro', icon: '📻', sounds: [
      s('vinyl_crackle', 'Vinyl Crackle', 'retro', '唱片', 'noise', 'Old record', { filter: 2500, lfoRate: 0.8, lfoDepth: 0.1 }),
      s('radio_static', 'Radio Static', 'retro', '📻', 'noise', 'AM tuning', { filter: 2000, lfoRate: 0.5, lfoDepth: 0.15 }),
      s('cassette', 'Cassette Hiss', 'retro', '📼', 'noise', 'Tape noise', { filter: 3000, lfoRate: 0.3, lfoDepth: 0.08 }),
      s('typewriter', 'Typewriter', 'retro', '⌨️', 'chime', 'Keys clacking', { freq: 1500, lfoRate: 0.6, lfoDepth: 0.3 }),
      s('dial_up', 'Dial-up Modem', 'retro', '📞', 'chime', 'Internet sound', { freq: 1800, lfoRate: 0.8, lfoDepth: 0.4 }),
      s('rotary_phone', 'Rotary Phone', 'retro', '☎️', 'chime', 'Dial clicking', { freq: 800, lfoRate: 0.3, lfoDepth: 0.35 }),
      s('projector', 'Film Projector', 'retro', '📽️', 'noise', 'Old movie reel', { filter: 1200, lfoRate: 0.6, lfoDepth: 0.15 }),
      s('arcade', 'Arcade Hall', 'retro', '🕹️', 'noise', 'Retro gaming', { filter: 1400, lfoRate: 0.4, lfoDepth: 0.25 }),
      s('synthwave', 'Synthwave Drone', 'retro', '🎹', 'osc', '80s atmosphere', { freq: 110, lfoRate: 0.1, lfoDepth: 0.2 }),
      s('drive_in', 'Drive-in Movie', 'retro', '🚗', 'noise', 'Outdoor cinema', { filter: 900, lfoRate: 0.15, lfoDepth: 0.12 }),
    ],
  },
];

export const allAmbientSounds: AmbientSound[] = ambientCategories.flatMap((c) => c.sounds);

export function getAmbientSound(id: string): AmbientSound | undefined {
  return allAmbientSounds.find((snd) => snd.id === id);
}

export const totalAmbientCount = allAmbientSounds.length;
